apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-youtube
  template:
    metadata:
      labels:
        app: hello-youtube
    spec:
      containers:
      - name: hello-youtube-container
        image: gcr.io/project-456212/youtube-repo:$SHORT_SHA
        ports:
        - containerPort: 8080

